---
title: "Data_Analysis_gml"
author: "Wilmer"
date: "1/7/2020"
output: pdf_document
---

## Libraries
```{r}
library(igraph)
library(ggplot2)
library(gridExtra)
```

## Reading data

```{r pressure, echo=FALSE}
dataname <- "Marta_Rovira"
path_mr_in <- paste('../result/', 'Marta_Rovira', '-link-list_in.graphml', sep = '')
path_vaga_in <- paste('../result/', 'Vaga8Nov', '-link-list_in.graphml', sep = '')
path_nb_in <- paste('../result/', 'nochebuena', '-link-list_in.graphml', sep = '')
path_mr_out <- paste('../result/', 'Marta_Rovira', '-link-list_out.graphml', sep = '')
path_nb_out <- paste('../result/', 'nochebuena', '-link-list_out.graphml', sep = '')
path_vaga_out <- paste('../result/', 'Vaga8Nov', '-link-list_out.graphml', sep = '')
mr_in <- read.graph(path_mr_in, format = "graphml")
mr_out <- read.graph(path_mr_out, format = "graphml")
vaga_in <- read.graph(path_vaga_in, format = "graphml")
vaga_out <- read.graph(path_vaga_out, format = "graphml")
nb_in <- read.graph(path_nb_in, format = "graphml")
nb_out <- read.graph(path_nb_out, format = "graphml")
```

## Data
```{r}
V(mr_out)
E(mr_in)
```

## Attributes
```{r}
vertex_attr(mr_out, "community")
vertex_attr(mr_out, "participation index")
vertex_attr(mr_out, "dispersion index")
vertex_attr(mr_out, "global hubness")
vertex_attr(mr_out, "local hubness")


```

## Disperion vs GH
```{r}
p1 <- ggplot() + 
  geom_point(aes(vertex_attr(mr_out, "participation index"), vertex_attr(mr_out, "global hubness"), color = "points")) +
  ggtitle(paste("Out Degree", 'Marta_Rovira')) +
  labs(x = 'participation Index', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p2 <- ggplot() + 
  geom_point(aes(vertex_attr(vaga_out, "participation index"), vertex_attr(vaga_out, "global hubness"), color = "points")) +
  ggtitle("Out Degree Vaga8Nov") +
  labs(x = 'participation Index', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p3 <- ggplot() + 
  geom_point(aes(vertex_attr(nb_out, "participation index"), vertex_attr(nb_out, "global hubness"), color = "points")) +
  ggtitle("Out Degree nochebuena") +
  labs(x = 'participation Index', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

grid.arrange(p1, p2, p3, nrow = 1)


```

## Disperion vs GH
```{r}
p1 <- ggplot() + 
  geom_point(aes(vertex_attr(mr_in, "participation index"), vertex_attr(mr_in, "global hubness"), color = "points")) +
  ggtitle(paste("IN Degree", 'Marta_Rovira')) +
  labs(x = 'participation Index', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p2 <- ggplot() + 
  geom_point(aes(vertex_attr(vaga_in, "participation index"), vertex_attr(vaga_in, "global hubness"), color = "points")) +
  ggtitle("IN Degree Vaga8Nov") +
  labs(x = 'participation Index', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p3 <- ggplot() + 
  geom_point(aes(vertex_attr(nb_in, "participation index"), vertex_attr(nb_in, "global hubness"), color = "points")) +
  ggtitle("IN Degree nochebuena") +
  labs(x = 'participation Index', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p4 <- ggplot() + 
  geom_point(aes(vertex_attr(mr_in, "participation index"), vertex_attr(mr_in, "local hubness"), color = "points")) +
  ggtitle(paste("IN Degree", 'Marta_Rovira')) +
  labs(x = 'participation Index', y = 'local Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p5 <- ggplot() + 
  geom_point(aes(vertex_attr(vaga_in, "participation index"), vertex_attr(vaga_in, "local hubness"), color = "points")) +
  ggtitle("IN Degree Vaga8Nov") +
  labs(x = 'participation Index', y = 'local Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")

p6 <- ggplot() + 
  geom_point(aes(vertex_attr(nb_in, "participation index"), vertex_attr(nb_in, "local hubness"), color = "points")) +
  ggtitle("IN Degree nochebuena") +
  labs(x = 'participation Index', y = 'local Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")


grid.arrange(p1, p2, p3, nrow = 1)
grid.arrange(p4, p5, p6, nrow = 1)


```


## Plots for out degree
```{r}
png(filename=paste(dataname,"_lh_gh_out.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_out, "local hubness"), vertex_attr(mr_out, "global hubness"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Local Hubness', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

png(filename=paste(dataname,"_pi_gh_out.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_out, "participation index"), vertex_attr(mr_out, "global hubness"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Participation', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

png(filename=paste(dataname,"_pi_lh_out.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_out, "participation index"), vertex_attr(mr_out, "local hubness"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Participation', y = 'Local Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

png(filename=paste(dataname,"_pi_di_out.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_out, "participation index"), vertex_attr(mr_out, "dispersion index"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Participation', y = 'Disperion', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

```

# Plots for in degree
```{r}
png(filename=paste(dataname,"_lh_gh_in.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_in, "local hubness"), vertex_attr(mr_in, "global hubness"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Local Hubness', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

png(filename=paste(dataname,"_pi_gh_in.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_in, "participation index"), vertex_attr(mr_in, "global hubness"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Participation', y = 'Global Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

png(filename=paste(dataname,"_pi_lh_in.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_in, "participation index"), vertex_attr(mr_in, "local hubness"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Participation', y = 'Local Hubness', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()

png(filename=paste(dataname,"_pi_di_in.png", sep = ''))
ggplot() + 
  geom_point(aes(vertex_attr(mr_in, "participation index"), vertex_attr(mr_in, "dispersion index"), color = "points")) +
  ggtitle("Out Degree") +
  labs(x = 'Participation', y = 'Disperion', color="Legend") + scale_color_manual(values=c("#F8766D", "#00BFC4"))+
    theme(legend.position = "none")
dev.off()
```

